# Generated by Django 6.0.2 on 2026-02-24 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3388ff', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('unsolved', 'Unsolved'), ('solved', 'Solved')], default='unsolved', max_length=10)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='maps.barangay')),
            ],
            options={
                'ordering': ['barangay', 'number'],
                'unique_together': {('barangay', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.IntegerField()),
                ('owner', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('pin', models.CharField(blank=True, default='', max_length=50)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('assessment_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rpt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('land_use', models.JSONField(default=list)),
                ('area_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='maps.section')),
            ],
            options={
                'ordering': ['section', 'lot_number'],
                'unique_together': {('section', 'lot_number')},
            },
        ),
    ]
