# Generated by Django 6.0.2 on 2026-03-31 00:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_notification_passwordrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadAlalum',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'cad_alalum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CadMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('barangay_name', models.TextField()),
                ('source_file', models.TextField()),
                ('properties', models.JSONField(default=dict)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'cad_maps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PimBarangayBoundary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('barangay_name', models.TextField()),
                ('source_file', models.TextField()),
                ('properties', models.JSONField(default=dict)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'pim_barangay_boundaries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PimEnlargement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('barangay_name', models.TextField()),
                ('section_number', models.IntegerField()),
                ('source_file', models.TextField()),
                ('properties', models.JSONField(default=dict)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'pim_enlargements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PimSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('barangay_name', models.TextField()),
                ('section_number', models.IntegerField()),
                ('source_file', models.TextField()),
                ('properties', models.JSONField(default=dict)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'pim_sections',
                'managed': False,
            },
        ),
    ]
