# Generated by Django 6.0.2 on 2026-03-31 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_cadalalum_cadmap_pimbarangayboundary_pimenlargement_and_more'),
        ('maps', '0004_cadalalum_cadmap_pimbarangayboundary_pimenlargement_and_more'),
    ]

    operations = [
    ]
