# Generated by Django 6.0.4 on 2026-04-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_merge_20260331_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotadjustment',
            name='adjustment_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
